version: '3'
services:
  hydra-ws:
    build: .
    image: yuzhong1214/hydra-ws
    container_name: hydra-ws
    stdin_open: true
    tty: true
    privileged: true
    command: /bin/bash
    network_mode: host
    working_dir: /home/user/Hydra/hydra_ws
    environment:
      - DISPLAY=${DISPLAY}
      # ROS1 parameters
      - CATKIN_WS=/home/user/Hydra/hydra_ws
    # If you want to access GPU, please uncomment the lines below.
    # Reference : https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount Device
      - /dev:/dev
      # Mount Gazebo models directory to reuse models downloaded during first launch.
      # Reference: https://answers.ros.org/question/365658
      - ./cache/.gazebo:/home/user/.gazebo
      # Mount workspace
      - ../..:/home/user/Hydra
